
SELECT pitch_id, pitch_type, quad_nomid,

   MAX(CASE WHEN pitch_metric = 'plate_speed' THEN pitch_metric_value END) AS plate_speed,
   MAX(CASE WHEN pitch_metric = 'release_speed' THEN pitch_metric_value END) AS release_speed,

   MAX(CASE WHEN metric_name = 'hand_vel_total_at_release' THEN value END) AS hand_vel_total_at_release,
   MAX(CASE WHEN metric_name = 'hand_vel_x_at_release' THEN value END) AS hand_vel_x_at_release,
   MAX(CASE WHEN metric_name = 'hand_vel_y_at_release' THEN value END) AS hand_vel_y_at_release,
   MAX(CASE WHEN metric_name = 'hand_vel_z_at_release' THEN value END) AS hand_vel_z_at_release,
   
   MAX(CASE WHEN metric_name = 'hip_rotation_at_footplant' THEN value END) AS hip_rotation_at_footplant,
   MAX(CASE WHEN metric_name = 'hip_rotation_at_release' THEN value END) AS hip_rotation_at_release,
   MAX(CASE WHEN metric_name = 'hip_rotation_at_sit' THEN value END) AS hip_rotation_at_sit,
   MAX(CASE WHEN metric_name = 'hip_rotation_vel_at_footplant' THEN value END) AS hip_rotation_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'hip_rotation_vel_at_release' THEN value END) AS hip_rotation_vel_at_release,
   MAX(CASE WHEN metric_name = 'hip_rotation_vel_at_sit' THEN value END) AS hip_rotation_vel_at_sit,
   MAX(CASE WHEN metric_name = 'hip_tilt_at_footplant' THEN value END) AS hip_tilt_at_footplant,
   
   MAX(CASE WHEN metric_name = 'hip_tilt_at_release' THEN value END) AS hip_tilt_at_release,
   MAX(CASE WHEN metric_name = 'hip_tilt_at_sit' THEN value END) AS hip_tilt_at_sit,
   MAX(CASE WHEN metric_name = 'hip_tilt_vel_at_footplant' THEN value END) AS hip_tilt_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'hip_tilt_vel_at_release' THEN value END) AS hip_tilt_vel_at_release,
   MAX(CASE WHEN metric_name = 'hip_tilt_vel_at_sit' THEN value END) AS hip_tilt_vel_at_sit,
   
   MAX(CASE WHEN metric_name = 'lead_elbow_rot_at_footplant' THEN value END) AS lead_elbow_rot_at_footplant,
   MAX(CASE WHEN metric_name = 'lead_elbow_rot_at_release' THEN value END) AS lead_elbow_rot_at_release,
   MAX(CASE WHEN metric_name = 'lead_elbow_rot_at_sit' THEN value END) AS lead_elbow_rot_at_sit,
   MAX(CASE WHEN metric_name = 'lead_elbow_rot_vel_at_footplant' THEN value END) AS lead_elbow_rot_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'lead_elbow_rot_vel_at_release' THEN value END) AS lead_elbow_rot_vel_at_release,
   MAX(CASE WHEN metric_name = 'lead_elbow_rot_vel_at_sit' THEN value END) AS lead_elbow_rot_vel_at_sit,
   MAX(CASE WHEN metric_name = 'lead_elbow_tilt_at_footplant' THEN value END) AS lead_elbow_tilt_at_footplant,
   MAX(CASE WHEN metric_name = 'lead_elbow_tilt_at_release' THEN value END) AS lead_elbow_tilt_at_release,
   MAX(CASE WHEN metric_name = 'lead_elbow_tilt_at_sit' THEN value END) AS lead_elbow_tilt_at_sit,
   MAX(CASE WHEN metric_name = 'lead_elbow_tilt_vel_at_footplant' THEN value END) AS lead_elbow_tilt_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'lead_elbow_tilt_vel_at_release' THEN value END) AS lead_elbow_tilt_vel_at_sit,
   
   MAX(CASE WHEN metric_name = 'lead_wrist_rot_at_footplant' THEN value END) AS lead_wrist_rot_at_footplant,
   MAX(CASE WHEN metric_name = 'lead_wrist_rot_at_release' THEN value END) AS lead_wrist_rot_at_release,
   MAX(CASE WHEN metric_name = 'lead_wrist_rot_at_sit' THEN value END) AS lead_wrist_rot_at_sit,
   MAX(CASE WHEN metric_name = 'lead_wrist_rot_vel_at_footplant' THEN value END) AS lead_wrist_rot_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'lead_wrist_rot_vel_at_release' THEN value END) AS lead_wrist_rot_vel_at_release,
   MAX(CASE WHEN metric_name = 'lead_wrist_rot_vel_at_sit' THEN value END) AS lead_wrist_rot_vel_at_sit,
   MAX(CASE WHEN metric_name = 'lead_wrist_tilt_at_footplant' THEN value END) AS lead_wrist_tilt_at_footplant,
   MAX(CASE WHEN metric_name = 'lead_wrist_tilt_at_release' THEN value END) AS lead_wrist_tilt_at_release,
   MAX(CASE WHEN metric_name = 'lead_wrist_tilt_at_sit' THEN value END) AS lead_wrist_tilt_at_sit,
   MAX(CASE WHEN metric_name = 'lead_wrist_tilt_vel_at_footplant' THEN value END) AS lead_wrist_tilt_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'lead_wrist_tilt_vel_at_release' THEN value END) AS lead_wrist_tilt_vel_at_release,
   MAX(CASE WHEN metric_name = 'lead_wrist_tilt_vel_at_sit' THEN value END) AS lead_wrist_tilt_vel_at_sit,
   
   MAX(CASE WHEN metric_name = 'lelbow_flex_at_footplant' THEN value END) AS lelbow_flex_at_footplant,
   MAX(CASE WHEN metric_name = 'lelbow_flex_at_release' THEN value END) AS lelbow_flex_at_release,
   MAX(CASE WHEN metric_name = 'lelbow_flex_at_sit' THEN value END) AS lelbow_flex_at_sit,
   MAX(CASE WHEN metric_name = 'lelbow_flex_vel_at_footplant' THEN value END) AS lelbow_flex_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'lelbow_flex_vel_at_release' THEN value END) AS lelbow_flex_vel_at_release,
   MAX(CASE WHEN metric_name = 'lelbow_flex_vel_at_sit' THEN value END) AS lelbow_flex_vel_at_sit,
   
   MAX(CASE WHEN metric_name = 'lhip_horizontal_at_footplant' THEN value END) AS lhip_horizontal_at_footplant,
   MAX(CASE WHEN metric_name = 'lhip_horizontal_at_release' THEN value END) AS lhip_horizontal_at_release,
   MAX(CASE WHEN metric_name = 'lhip_horizontal_at_sit' THEN value END) AS lhip_horizontal_at_sit,
   MAX(CASE WHEN metric_name = 'lhip_horizontal_vel_at_footplant' THEN value END) AS lhip_horizontal_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'lhip_horizontal_vel_at_release' THEN value END) AS lhip_horizontal_vel_at_release,
   MAX(CASE WHEN metric_name = 'lhip_horizontal_vel_at_sit' THEN value END) AS lhip_horizontal_vel_at_sit,
   MAX(CASE WHEN metric_name = 'lhip_vertical_at_footplant' THEN value END) AS lhip_vertical_at_footplant,
   MAX(CASE WHEN metric_name = 'lhip_vertical_at_release' THEN value END) AS lhip_vertical_at_release,
   MAX(CASE WHEN metric_name = 'lhip_vertical_at_sit' THEN value END) AS lhip_vertical_at_sit,
   MAX(CASE WHEN metric_name = 'lhip_vertical_vel_at_footplant' THEN value END) AS lhip_vertical_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'lhip_vertical_vel_at_release' THEN value END) AS lhip_vertical_vel_at_release,
   MAX(CASE WHEN metric_name = 'lhip_vertical_vel_at_sit' THEN value END) AS lhip_vertical_vel_at_sit,
   
   MAX(CASE WHEN metric_name = 'lknee_flex_at_footplant' THEN value END) AS lknee_flex_at_footplant,
   MAX(CASE WHEN metric_name = 'lknee_flex_at_release' THEN value END) AS lknee_flex_at_release,
   MAX(CASE WHEN metric_name = 'lknee_flex_at_sit' THEN value END) AS lknee_flex_at_sit,
   MAX(CASE WHEN metric_name = 'lknee_flex_vel_at_footplant' THEN value END) AS lknee_flex_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'lknee_flex_vel_at_release' THEN value END) AS lknee_flex_vel_at_release,
   MAX(CASE WHEN metric_name = 'lknee_flex_vel_at_sit' THEN value END) AS lknee_flex_vel_at_sit,
   MAX(CASE WHEN metric_name = 'lshoulder_horizontal_at_footplant' THEN value END) AS lshoulder_horizontal_at_footplant,
   
   MAX(CASE WHEN metric_name = 'lshoulder_horizontal_at_release' THEN value END) AS lshoulder_horizontal_at_release,
   MAX(CASE WHEN metric_name = 'lshoulder_horizontal_at_sit' THEN value END) AS lshoulder_horizontal_at_sit,
   MAX(CASE WHEN metric_name = 'lshoulder_horizontal_vel_at_footplant' THEN value END) AS lshoulder_horizontal_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'lshoulder_horizontal_vel_at_release' THEN value END) AS lshoulder_horizontal_vel_at_release,
   MAX(CASE WHEN metric_name = 'lshoulder_horizontal_vel_at_sit' THEN value END) AS lshoulder_horizontal_vel_at_sit,
   MAX(CASE WHEN metric_name = 'lshoulder_vertical_at_footplant' THEN value END) AS lshoulder_vertical_at_footplant,
   MAX(CASE WHEN metric_name = 'lshoulder_vertical_at_release' THEN value END) AS lshoulder_vertical_at_release,
   MAX(CASE WHEN metric_name = 'lshoulder_vertical_at_sit' THEN value END) AS lshoulder_vertical_at_sit,
   MAX(CASE WHEN metric_name = 'lshoulder_vertical_vel_at_footplant' THEN value END) AS lshoulder_vertical_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'lshoulder_vertical_vel_at_release' THEN value END) AS lshoulder_vertical_vel_at_release,
   MAX(CASE WHEN metric_name = 'lshoulder_vertical_vel_at_sit' THEN value END) AS lshoulder_vertical_vel_at_sit,
   
   MAX(CASE WHEN metric_name = 'relbow_flex_at_release' THEN value END) AS relbow_flex_at_release,
   MAX(CASE WHEN metric_name = 'relbow_flex_at_sit' THEN value END) AS relbow_flex_at_sit,
   MAX(CASE WHEN metric_name = 'relbow_flex_at_footplant' THEN value END) AS relbow_flex_at_footplant,
   MAX(CASE WHEN metric_name = 'relbow_flex_vel_at_footplant' THEN value END) AS relbow_flex_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'relbow_flex_vel_at_release' THEN value END) AS relbow_flex_vel_at_release,
   MAX(CASE WHEN metric_name = 'relbow_flex_vel_at_sit' THEN value END) AS relbow_flex_vel_at_sit,
   MAX(CASE WHEN metric_name = 'release_time' THEN value END) AS release_time,
   
   MAX(CASE WHEN metric_name = 'rhip_horizontal_at_footplant' THEN value END) AS rhip_horizontal_at_footplant,
   MAX(CASE WHEN metric_name = 'rhip_horizontal_at_release' THEN value END) AS rhip_horizontal_at_release,
   MAX(CASE WHEN metric_name = 'rhip_horizontal_at_sit' THEN value END) AS rhip_horizontal_at_sit,
   MAX(CASE WHEN metric_name = 'rhip_horizontal_vel_at_footplant' THEN value END) AS rhip_horizontal_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'rhip_horizontal_vel_at_release' THEN value END) AS rhip_horizontal_vel_at_release,
   MAX(CASE WHEN metric_name = 'rhip_horizontal_vel_at_sit' THEN value END) AS rhip_horizontal_vel_at_sit,
   MAX(CASE WHEN metric_name = 'rhip_vertical_at_footplant' THEN value END) AS rhip_vertical_at_footplant,
   MAX(CASE WHEN metric_name = 'rhip_vertical_at_release' THEN value END) AS rhip_vertical_at_release,
   MAX(CASE WHEN metric_name = 'rhip_vertical_at_sit' THEN value END) AS rhip_vertical_at_sit,
   MAX(CASE WHEN metric_name = 'rhip_vertical_vel_at_footplant' THEN value END) AS rhip_vertical_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'rhip_vertical_vel_at_release' THEN value END) AS rhip_vertical_vel_at_release,
   MAX(CASE WHEN metric_name = 'rhip_vertical_vel_at_sit' THEN value END) AS rhip_vertical_vel_at_sit,
   MAX(CASE WHEN metric_name = 'rhip_horizontal_vel_at_release' THEN value END) AS rhip_horizontal_vel_at_release,
   
   MAX(CASE WHEN metric_name = 'rknee_flex_at_footplant' THEN value END) AS rknee_flex_at_footplant,
   MAX(CASE WHEN metric_name = 'rknee_flex_at_release' THEN value END) AS rknee_flex_at_release,
   MAX(CASE WHEN metric_name = 'rknee_flex_at_sit' THEN value END) AS rknee_flex_at_sit,
   MAX(CASE WHEN metric_name = 'rknee_flex_vel_at_footplant' THEN value END) AS rknee_flex_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'rknee_flex_vel_at_release' THEN value END) AS rknee_flex_vel_at_release,
   MAX(CASE WHEN metric_name = 'rknee_flex_vel_at_sit' THEN value END) AS rknee_flex_vel_at_sit,
   
   MAX(CASE WHEN metric_name = 'rshoulder_horizontal_at_footplant' THEN value END) AS rshoulder_horizontal_at_footplant,
   MAX(CASE WHEN metric_name = 'rshoulder_horizontal_at_release' THEN value END) AS rshoulder_horizontal_at_release,
   MAX(CASE WHEN metric_name = 'rshoulder_horizontal_at_sit' THEN value END) AS rshoulder_horizontal_at_sit,
   MAX(CASE WHEN metric_name = 'rshoulder_horizontal_vel_at_footplant' THEN value END) AS rshoulder_horizontal_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'rshoulder_horizontal_vel_at_release' THEN value END) AS rshoulder_horizontal_vel_at_release,
   MAX(CASE WHEN metric_name = 'rshoulder_horizontal_vel_at_sit' THEN value END) AS rshoulder_horizontal_vel_at_sit,
   MAX(CASE WHEN metric_name = 'rshoulder_vertical_at_footplant' THEN value END) AS rshoulder_vertical_at_footplant,
   MAX(CASE WHEN metric_name = 'rshoulder_vertical_at_release' THEN value END) AS rshoulder_vertical_at_release,
   MAX(CASE WHEN metric_name = 'rshoulder_vertical_at_sit' THEN value END) AS rshoulder_vertical_at_sit,
   MAX(CASE WHEN metric_name = 'rshoulder_vertical_vel_at_footplant' THEN value END) AS rshoulder_vertical_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'rshoulder_vertical_vel_at_release' THEN value END) AS rshoulder_vertical_vel_at_release,
   MAX(CASE WHEN metric_name = 'rshoulder_vertical_vel_at_sit' THEN value END) AS rshoulder_vertical_vel_at_sit,
   
   MAX(CASE WHEN metric_name = 'stride_direction' THEN value END) AS stride_direction,
   MAX(CASE WHEN metric_name = 'stride_length' THEN value END) AS stride_length,
   MAX(CASE WHEN metric_name = 'time_at_footplant' THEN value END) AS time_at_footplant,
   MAX(CASE WHEN metric_name = 'time_at_sit' THEN value END) AS time_at_sit,
   
   MAX(CASE WHEN metric_name = 'torso_flexion_at_footplant' THEN value END) AS torso_flexion_at_footplant,
   MAX(CASE WHEN metric_name = 'torso_flexion_at_release' THEN value END) AS torso_flexion_at_release,
   MAX(CASE WHEN metric_name = 'torso_flexion_at_sit' THEN value END) AS torso_flexion_at_sit,
   MAX(CASE WHEN metric_name = 'torso_flexion_vel_at_footplant' THEN value END) AS torso_flexion_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'torso_flexion_vel_at_release' THEN value END) AS torso_flexion_vel_at_release,
   MAX(CASE WHEN metric_name = 'torso_flexion_vel_at_sit' THEN value END) AS torso_flexion_vel_at_sit,
   MAX(CASE WHEN metric_name = 'torso_rotation_at_footplant' THEN value END) AS torso_rotation_at_footplant,
   MAX(CASE WHEN metric_name = 'torso_rotation_at_release' THEN value END) AS torso_rotation_at_release,
   MAX(CASE WHEN metric_name = 'torso_rotation_at_sit' THEN value END) AS torso_rotation_at_sit,
   MAX(CASE WHEN metric_name = 'torso_rotation_vel_at_footplant' THEN value END) AS torso_rotation_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'torso_rotation_vel_at_release' THEN value END) AS torso_rotation_vel_at_release,
   MAX(CASE WHEN metric_name = 'torso_rotation_vel_at_sit' THEN value END) AS torso_rotation_vel_at_sit,
   MAX(CASE WHEN metric_name = 'torso_tilt_at_footplant' THEN value END) AS torso_tilt_at_footplant,
   MAX(CASE WHEN metric_name = 'torso_tilt_at_release' THEN value END) AS torso_tilt_at_release,
   MAX(CASE WHEN metric_name = 'torso_tilt_at_sit' THEN value END) AS torso_tilt_at_sit,
   MAX(CASE WHEN metric_name = 'torso_tilt_vel_at_footplant' THEN value END) AS torso_tilt_vel_at_footplant,
   MAX(CASE WHEN metric_name = 'torso_tilt_vel_at_release' THEN value END) AS torso_tilt_vel_at_release,
   MAX(CASE WHEN metric_name = 'torso_tilt_vel_at_sit' THEN value END) AS torso_tilt_vel_at_sit
   
FROM pitches
GROUP BY pitch_id;